import { Theme } from './type';

export const THEME: Theme = {
  ACCENT_COLOR: '#30A99B',
  BLACK_COLOR: '#000',
  BORDER_COLOR: '#b3b3b3',
  DISABLED_COLOR: '#d3d3d3',
  ERROR_COLOR: '#a3314f',
  MAIN_BACKGROUND_COLOR: '#FFF',
  PRIMARY_COLOR: '#F16A6A',
  PRIMARY_TEXT_COLOR_COLOR: '#3e3e3e',
  SECONDARY_BACKGROUND_COLOR: '#f1f1f1',
  SECONDARY_COLOR: '#076587',
  SECONDARY_TEXT_COLOR: '#e3e3e3',
  SUCCESS_COLOR: '#009688',
  WARNING_COLOR: '#ff9800',
  WHITE: '#FFF',
};
