name: 'Publish new alpha version'

on:
  push:
    branches: [develop]

env:
  CACHE_NAME: 'CACHE_NODE_MODULES'
  NODE_VERSION: '12.x'

jobs:
  deploy-alpha-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true 
      - name: 'Get yarn cache path'
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-   
            ${{ runner.os }}-build- 
            ${{ runner.os }}-
      - name: 'Install packages'
        run: yarn --frozen-lockfile --prefer-offline
      - name: 'Release to alpha'
        run: expo publish --non-interactive --release-channel alpha
