name: 'Publish production version'

on:
  push:
    branches: [master]

env:
  CACHE_NAME: 'CACHE_NODE_MODULES'
  NODE_VERSION: '12.x'

jobs:
  deploy-production-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true 
      - name: 'Get last rc publish'
        id: publish
        run: echo "::set-output name publish-id::$(expo publish:history --release-channel rc --count 1 --raw)"
      - name: 'Set publish id on production'
        run: expo publish:set --release-channel production --publish-id ${{fromJSON(steps.publish.outputs).queryResult[0].publicationId}}

