name: 'Close release candidate'

on:
  pull_request:
    types: [labeled]
    branches: [master]

env:
  CACHE_NAME: 'CACHE_NODE_MODULES'
  NODE_VERSION: '12.x'

jobs:
  deploy-production-version:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/') && contains(github.event.label.name, 'release/finish')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'Get yarn cache path'
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-   
            ${{ runner.os }}-build- 
            ${{ runner.os }}-
      - name: 'Install packages'
        run: yarn --frozen-lockfile --prefer-offline
      - name: 'Create tag and bump version'
        run: yarn standard-version
      - name: Push changes
        run: git push --follow-tags
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_DELETE_BRANCH: true
          MERGE_LABELS: "release/finish"

